apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJzdWhhaWxha3RoYXIiLCJwYXNzd29yZCI6ImRja3JfcGF0X28zbzVPVWg0SUgzdl9HMmdqWjJxMkZURTZaTSIsImVtYWlsIjoiMTIzQGdtYWlsLmNvbSIsImF1dGgiOiJjM1ZvWVdsc1lXdDBhR0Z5T21SamEzSmZjR0YwWDI4emJ6VlBWV2cwU1VnemRsOUhNbWRxV2pKeE1rWlVSVFphVFE9PSJ9fX0=
